### ISSUE TITLE
Empty /tmp folders are not deployed

### ISSUE THREAD

**Issue by JanSlabon** [Setasign/SetaPDF-Demos#3]
E.g. here: https://demos.setasign.com/?p=%2Fdemo%2F5-Signer%2F1-standard-signatures%2F7-async-signature-and-timestamp
and here: https://demos.setasign.com/?p=%2Fdemo%2F5-Signer%2F2-visible-signatures%2F8-async-visible-signature-and-timestamp

**Comment by MaximilianKresse** [comment]
Empty /tmp folders should have a .gitignore file like this:
```
# Ignore everything in this directory
*
# Except this file
!.gitignore
```

**Comment by MaximilianKresse** [comment]
Fixed
